### ISSUE TITLE
Great Idea for WP-A.co

### ISSUE THREAD

**Issue by vmesel** [ghurl/db#55]
Hello my friend!

Tudo bem Gustavo?

Estou vendo que você fez um shortener distribuído e gostaria de uma ajuda sua já que eu tenho um projeto de Shortener distribuído chamado [WP-A.CO](http://www.github.com/vmesel/WP-A.CO/), você teria como me ajudar a desenvolver a distribuição deste software?

**Comment by gberger** [comment]
Oi Vinicius, sou o autor do projeto, se quiser entre em contato comigo em guilherme.berger@gmail.com
